captest:
  test_setup: bifi_e2848_etotal_rear_shade_sim
  meas_path: ./data/example_meas_data_bifi.csv
  sim_path: ./data/pvsyst_example_HourlyRes_2_bifi.CSV
  rc_source: meas
  ac_nameplate: 6000
  inv_ac_nameplate: null
  test_tolerance: +/- 3
  sim_days: 30
  shade_filter_start: null
  shade_filter_end: null
  min_irr: 400
  max_irr: 1400
  clipping_irr: 1000
  rep_irr_filter: 0.2
  fshdbm: 1.0
  irrad_stability: std
  irrad_stability_threshold: 30
  hrs_req: 12.5
  bifaciality: 0.7
  bifacial_frac: 1.0
  rear_shade: 0.0
  power_temp_coeff: -0.32
  base_temp: 25
  module_type: glass_cell_poly
  racking: open_rack
  spectral_module_type: cdte
  airmass_model: kastenyoung1989
  altitude_override: 0
  meas_load_kwargs:
    group_columns: ./data/column_groups_bifi.xlsx
  meas_filters:
  - type: Custom
    func: pandas.core.frame:DataFrame.dropna
    args: []
    kwargs: {}
    custom_name: null
  - type: Irradiance
    col_name: null
    custom_name: null
    high: 1400
    low: 400
    ref_val: null
    units: W/m^2
  - type: Outliers
    custom_name: null
    envelope_kwargs: null
  - type: Regression
    custom_name: null
    n_std: 2
  - type: RepCond
    custom_name: null
    front_poa: poa
    func: null
    irr_bal: false
    percent_filter: 20
    rc_kwargs: null
    w_vel: null
  - type: Irradiance
    col_name: null
    custom_name: null
    high: 1.2
    low: 0.8
    ref_val: rep_irr
    units: W/m^2
  sim_filters:
  - type: Time
    custom_name: null
    days: 30
    drop: false
    end: null
    start: null
    test_date: 10/11/1990
  - type: Irradiance
    col_name: null
    custom_name: null
    high: 930
    low: 400
    ref_val: null
    units: W/m^2
  - type: Pvsyst
    custom_name: null
  - type: Irradiance
    col_name: null
    custom_name: null
    high: 1.2
    low: 0.8
    ref_val: rep_irr
    units: W/m^2
